FROM openjdk:7

LABEL maintainer="KalimGit"

VOLUME /tmp

ADD target/SampleDockerSpringApp-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8081

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]